# Generated by Django 4.1.1 on 2022-11-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_order_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="interested",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
