# Generated by Django 4.1.1 on 2022-11-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_order_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="status_date", field=models.DateField(blank=True),
        ),
    ]
