# Generated by Django 4.1.1 on 2022-11-26 22:08

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_order_status_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                default=100, validators=[myapp.models.validate_stock]
            ),
        ),
    ]
