# Generated by Django 4.1.1 on 2022-11-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
